[package]
name = "bvh2d"
description = "A fast BVH using SAH for 2d"
version = "0.3.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/mockersf/bvh2d"
documentation = "https://docs.rs/crate/bvh2d"
license = "MIT"

[dependencies]
glam = "0.23"
